Throw error on division by 0 for rationals
Plutonomicon/plutarch pull request #299
Opened 2022-02-16 21:03 UTC by Geometer1729

I noticed down stream that rationals weren't throwing an error on division by 0 like I expected, so I added some tests and fixed it so they do.

2022-02-16 23:03 UTC, srid submitted a review, later dismissed

2022-02-16 23:03 UTC, srid commented on plutarch-test/src/Plutarch/RationalSpec.hs
> +    describe "div by 0 tests" $ do
nit: the " tests" suffix is redundant.

2022-02-17 21:48 UTC, srid approved these changes

2022-02-17 21:52 UTC, L-as commented
CI hasn't run

2022-02-18 09:13 UTC, L-as commented
Goldens need to be updated

2022-02-18 09:15 UTC, L-as requested changes
See above

2022-02-18 09:26 UTC, L-as requested changes

2022-02-18 09:26 UTC, L-as commented on Plutarch/Rational.hs
> +          (pcon $ PRational (s * pdiv # xn # r) (s * pdiv # xd # r))
Unnecessary parentheses?

2022-02-18 09:26 UTC, L-as commented on plutarch-test/goldens/rational.ops.bench.golden
> +* {"exBudgetCPU":55159921,"exBudgetMemory":128071,"scriptSizeBytes":374}
This is quite unfortunate

2022-04-08 08:40 UTC, TotallyNotChase commented
continued in #427

2022-04-08 08:40 UTC, closed without merging