Mario/open letrec fix
Plutonomicon/plutarch pull request #453
Opened 2022-04-20 22:26 UTC by blamario

Two `letrec` fixes, for bugs discovered on PR #396 .

2022-04-20 22:46 UTC, L-as approved these changes
LGTM

2022-04-20 22:47 UTC, L-as requested changes
CI is failing

2022-04-20 23:37 UTC, blamario commented
CI is fixed.

2022-04-21 21:28 UTC, L-as approved these changes
LGTM

2022-04-21 21:28 UTC, merged