Haddock docs, minor `examples` reorganisation
Plutonomicon/plutarch pull request #49
Opened 2022-01-03 18:30 UTC by t1lde

Added some haddock docs, and some (small) relevant examples.

WIP - some more things could use doc comments, and the `Examples` modules may not be the best place to keep the examples (would be nice to better expose them to haddock...)

2022-01-03 18:36 UTC, L-as commented
Why is this a draft?

2022-01-03 18:38 UTC, L-as commented on examples/Examples/PlutusType.hs
> +  type PInner AB _ = PInteger
This is quite clever.

2022-01-04 10:07 UTC, t1lde commented
Put this up as draft before I logged off last night, but it should be ready ig.

Will fix formatting.

2022-01-04 10:35 UTC, t1lde commented
Looks like there's a fourmolu idempotentcy bug, something to do with Haddock that appears to be fixed in fourmolu 0.4.0.0, which hasn't made it's way into nixpkgs yet :upside_down_face:

2022-01-04 14:22 UTC, L-as commented
We need to use `fourmolu_0_4_0_0` instead of `fourmolu` in our Flake.

2022-01-04 14:54 UTC, L-as commented
See 8e815b11eed5ac324e570a88647ae3af574d5c79 from tmp branch. You can `git reset` to this.

2022-01-04 14:55 UTC, L-as commented
Nevermind, CI still fails...

2022-01-04 15:10 UTC, L-as commented
See 47775379dacb21944043bc3ea044cb18cf1bca3d instead, apparently `fourmolu_0_4_0_0` is broken on NIxpkgs. We could include it using `haskell.nix`, but :shrug: for now.

2022-01-04 15:56 UTC, TotallyNotChase requested changes
Looks great! The haddocks and examples are going to very useful for #55 as well.

2022-01-04 15:56 UTC, TotallyNotChase commented on Plutarch.hs
> +  -- | Construct a Plutarch Term via a Haskell value
I think this one needs to be updated.

2022-01-05 13:10 UTC, t1lde commented on Plutarch.hs
> +  -- | Construct a Plutarch Term via a Haskell value
Done

2022-01-05 13:54 UTC, merged

2022-01-05 13:55 UTC, L-as commented
I just noticed you made this merge into `staging`, but `staging` is just my personal playground currently... this is also on me lol.