Actually evaluate a script
Plutonomicon/plutarch pull request #8
Opened 2021-12-14 20:46 UTC by srid

Quick change to evaluate a simple Plutarch script.

(This actually fails to evaluate, see #9. Also note that the fib test is failing; all this goes to indicate the importance of #6 )

2021-12-14 22:47 UTC, L-as commented
I want this to be fixed before this is merged, as it's likely `evaluateScript` that is problematic. If you look at it, you'll notice that it converts it to a named AST, but that conversion isn't actually correct, perhaps because we're calling it wrong. The evaluation should work once you fix that.

2021-12-14 22:59 UTC, L-as requested changes
See comment.

2021-12-15 00:16 UTC, srid commented
> I want this to be fixed before this is merged, as it's likely `evaluateScript` that is problematic. If you look at it, you'll notice that it converts it to a named AST, but that conversion isn't actually correct, perhaps because we're calling it wrong. The evaluation should work once you fix that.

I don't think this is correct. Why do you think `evaluateScript` (named AST conversion is internal to it) is problematic here? We copied it verbatim (except for error handling, and returning result) from Plutus which uses this function to execute the validator `Script` (see [here](https://github.com/input-output-hk/plutus/blob/27e29cf134ddbf41fba6a51b173bd0e1aff71c28/plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs#L407-L416) and [here](https://github.com/input-output-hk/plutus/blob/27e29cf134ddbf41fba6a51b173bd0e1aff71c28/plutus-ledger-api/src/Plutus/V1/Ledger/Scripts.hs#L194-L206)). Furthermore, Pluto generates the correct `Script` that executes correctly by `evaluateScript` *as well as* by Plutus' emulator and contract test ([see here](https://github.com/Plutonomicon/pluto/tree/main/examples/contracts/sample)).

My guess was that debruijn index calculation was wrong somewhere, but I'll have to poke a bit more on this.

2021-12-15 14:14 UTC, L-as commented
7661c899958c5c09760efd18fdcaef613f41acaa

2021-12-15 14:14 UTC, closed without merging